name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t mei .
    - name: Run tests
      run: docker run --entrypoint pytest mei
