name: Test

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  test:
    if: github.repository_owner == 'sinzlab'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: touch .env && docker-compose run pytest
